
import java.awt.Color;
import java.awt.Dimension;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author David
 */
public class buttonInterface extends javax.swing.JFrame {

    /**
     * Creates new form buttonInterface
     */
	Radar radar;
	Handler handler;
	
	
    public buttonInterface(Radar radar)
    {
    	this.radar = radar;
    	handler = radar.handler;
        initComponents();
        Dimension screenSize = getToolkit().getScreenSize();
		setBounds(screenSize.width - 1040, 1040, 1040, 360);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        speed = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        Altitude = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        landButton = new javax.swing.JButton();
        takeOffButton = new javax.swing.JButton();
        demoLand = new javax.swing.JButton();
        demoDeparture = new javax.swing.JButton();
        demoCollision = new javax.swing.JButton();
        demoCrash = new javax.swing.JButton();
        exitAirspace = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        speed.setMajorTickSpacing(50);
        speed.setMaximum(250);
        speed.setOrientation(javax.swing.JSlider.VERTICAL);
        speed.setPaintLabels(true);
        speed.setPaintTicks(true);
        speed.setValue(75);
        speed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                speedMouseReleased(evt);
            }
        });

        jLabel1.setText("speed (Knots)");

        Altitude.setMajorTickSpacing(2000);
        Altitude.setMaximum(10000);
        Altitude.setOrientation(javax.swing.JSlider.VERTICAL);
        Altitude.setPaintLabels(true);
        Altitude.setPaintTicks(true);
        Altitude.setValue(4000);
        Altitude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                AltitudeMouseReleased(evt);
            }
        });

        jLabel2.setText("Altitude (ft)");

        jToggleButton1.setBackground(java.awt.Color.green);
        jToggleButton1.setSelected(true);
        jToggleButton1.setText("On");
        jToggleButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jToggleButton1StateChanged(evt);
            }
        });
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Collision Avoidance");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setToolTipText("");
        jList1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Potential Runway Queue");

        landButton.setBackground(new java.awt.Color(153, 153, 255));
        landButton.setText("Land");
        landButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landButtonActionPerformed(evt);
            }
        });

        takeOffButton.setBackground(new java.awt.Color(153, 153, 255));
        takeOffButton.setText("Takeoff");
        takeOffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeOffButtonActionPerformed(evt);
            }
        });

        demoLand.setBackground(new java.awt.Color(153, 255, 255));
        demoLand.setText("Demo Land");
        demoLand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoLandActionPerformed(evt);
            }
        });

        demoDeparture.setBackground(new java.awt.Color(153, 255, 255));
        demoDeparture.setText("Demo Departure");
        demoDeparture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoDepartureActionPerformed(evt);
            }
        });

        demoCollision.setBackground(new java.awt.Color(153, 255, 255));
        demoCollision.setText("Demo Collision avoid");
        demoCollision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoCollisionActionPerformed(evt);
            }
        });

        demoCrash.setBackground(new java.awt.Color(153, 255, 255));
        demoCrash.setText("Demo Crash");
        demoCrash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                demoCrashActionPerformed(evt);
            }
        });

        exitAirspace.setBackground(new java.awt.Color(153, 153, 255));
        exitAirspace.setText("Exit Airspace");
        exitAirspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAirspaceActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.Color.green);
        jButton1.setText("On");
        buttonGroup1.add(jButton1);
        jButton1.setSelected(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.gray);
        jButton2.setText("Off");
        buttonGroup1.add(jButton2);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(landButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(takeOffButton, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Altitude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(193, 193, 193))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jToggleButton1)
                                .addGap(217, 217, 217))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exitAirspace)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(demoLand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(demoCollision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(demoDeparture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(demoCrash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Altitude, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(landButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takeOffButton)
                        .addGap(4, 4, 4)
                        .addComponent(exitAirspace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(demoLand)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(demoDeparture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(demoCollision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(demoCrash)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //Place the code for speed when mouse release action 
    private void speedMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speedMouseReleased
        
    }//GEN-LAST:event_speedMouseReleased
//Place the code for altitude when mouse release action 
    private void AltitudeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AltitudeMouseReleased
        
    }//GEN-LAST:event_AltitudeMouseReleased

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    
    //place code for the collision avoidance detection system here.
    private void jToggleButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jToggleButton1StateChanged
        if(jToggleButton1.isSelected()) //code for if the collision avoidance is on
        {
            jToggleButton1.setText("On");
            jToggleButton1.setBackground(Color.green);
            
        }
        else //code if it is off
        {
            jToggleButton1.setText("Off");
            jToggleButton1.setBackground(Color.red);
        }
    }//GEN-LAST:event_jToggleButton1StateChanged

    
    
    
    
    
    
    
    
    //insert code for takeoff stuff
    private void landButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
    	for (Plane plane : handler.planeList)
    	{
    		if (plane.isSelected)
    		{
    			plane.joinQueueToLandRequest();
    		}
    	}
    }

    
    
    
    
    //Insert code for landing protocal
    private void takeOffButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
    	{
        	for (Plane plane : handler.planeList)
        	{
        		if (plane.isSelected)
        		{
        			plane.joinQueueToTakeoffRequest();
        		}
        	}
        }
    }

    
    //potential buttons to demo code.  Demo landing goes below
    private void demoLandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoLandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demoLandActionPerformed
    //Demo departure goes below
    private void demoDepartureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoDepartureActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demoDepartureActionPerformed
    //demo collision avoidance goes below
    private void demoCollisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoCollisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demoCollisionActionPerformed
    //demo Crash below
    private void demoCrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_demoCrashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_demoCrashActionPerformed

    
    //code to send to exit goes below
    private void exitAirspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAirspaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitAirspaceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setBackground(Color.green);
        jButton2.setBackground(Color.gray);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        jButton1.setBackground(Color.gray);
        jButton2.setBackground(Color.red);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Altitude;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton demoCollision;
    private javax.swing.JButton demoCrash;
    private javax.swing.JButton demoDeparture;
    private javax.swing.JButton demoLand;
    private javax.swing.JButton exitAirspace;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton landButton;
    private javax.swing.JSlider speed;
    private javax.swing.JButton takeOffButton;
    // End of variables declaration//GEN-END:variables
}
